name: Unit tests

on: [ push ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3
      - name: "Set up Python 3.10"
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: "Add conda to system path"
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: "Setup Backend"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pip install -r requirements.txt
      - name: "Backend Unit tests"
        run: |
          python -m pytest tests/unit
      - name: "Backend Unit tests Code Coverage"
        run: |
          python -m pytest tests/unit \
            --cov-report html:tests/reports/coverage/htmlcov \
            --cov-report xml:tests/reports/coverage/cobertura-coverage.xml \
            --cov-report term \
            --cov=src